print(".--~~--.    ...----~~~~~~------.........------~~~~~~----...    .--~~--.- ")
print("|        |  |         ____  ____  ____  ____                |  |        |")
print("|        `--'         l   l l   l l   l l   l   l           `--'        |")
print("|        |  |         l___l l   l l   l l___l   l           |  |        |")
print("|        |  |         l     l   l l   l l       l           |  |        |")
print("|        |  |         l     l___l l___l l       o           |  |        |")
print("|        |  |             INSIDE THY TOILET                 |  |        |")
print("|.--~~--.|  |...----~~~~~~------.........------~~~~~~----...|  |.--~~--.|")
print("        '.__.`                                             '.__.`        ")
print("         _____                                                           ")                  
print("        l_____l                                                          ")
print("       l-_____-l  /\/\/\/\/\/\/  _________                              ")
print("     l-_________-l    /\/\/\/\/\/I           \        /\        /       ")
print("    l-___________-l              I            \      /  \      /        ")
print("   l-_____________-l   /\/\/\/\  I_____        \    /    \    /         ")
print("  l-_______________-l            I              \  /      \  /          ")
print("                                 I________       \/        \/           ")
print(" welcome to Poop Cavern Stories generator!!!")
a=input("choose your character! a= elf b=human c=cat d=ghost")
if a==("a"):
    b=input(" choose a power a= ice freeze b=invisibility c= flying d= mind reading")
    if b==("a"):
        print("As the elf with freeze ray powers, you bravely step into the swirling rivers of poop.")
        print("With a wave of your hand, you freeze the stinky currents, creating a safe path of ice.")
        print("Each step echoes through the foul cavern, but your powers keep you clean and safe.")
        print("Suddenly, a poop monster rises from the sludge! You blast it with your freeze ray, turning it into a harmless poop-sicle.")
        print("Victorious, you skate across the frozen poop, searching for your next adventure!")
    if b==("b"):
        print("As the elf with invisibility powers, you silently tiptoe into the cavern of swirling poop rivers.")
        print("No one can see you—not even the poop monsters lurking in the shadows.")
        print("You sneak past the foul creatures, holding your nose and giggling at your own cleverness.")
        print("Suddenly, you spot a treasure chest buried beneath a pile of poop! You quietly open it, finding magical soap that cleans anything.")
        print("With your new prize, you slip away unseen, cleaning the insides of the intestines, clearing the way of poop, ready for more invisible adventures!")
    if b==("c"):
        print("the elf with flying powers soars above the rivers of poop, her wings shimmering in the dim cavern light.")
        print("From high above, she studies the swirling patterns and mysterious movements of the poop below, taking careful notes in her magical notebook.")
        print("she discovers that the poop currents reveal ancient secrets—hidden messages from elves long ago!")
        print("Excited by her findings, she swoops down for a closer look, dodging poop monsters and collecting rare samples for her research.")
        print("With her flying skills and scientific curiosity, she becomes the world's first poopologist elf, unlocking mysteries that no one else dares to explore!")
    if b==("d"):
        print("As the elf with mind reading powers, you step boldly into the winding tunnels of the digestive system.")
        print("You sense the thoughts of mysterious creatures lurking in the shadows—hungry bacteria, mischievous enzymes, and ancient gut spirits.")
        print("With each step, you read the minds of the cells around you, learning their secrets and discovering hidden passageways.")
        print("Suddenly, you hear the worried thoughts of a friendly probiotic, trapped by a mischievous stomach acid monster!")
        print("Using your mind reading powers, you outsmart the monster, freeing the probiotic and earning its gratitude.")
        print("Together, you journey deeper, unlocking the mysteries of the digestive realm and forging magical friendships along the way!")
if a==("b"):
    c=input("choose ability a= athletic b= good memory c= insane detective skill d= brainy")
    if c==("a"):
        p=input("choose a name")
        print(p+", you leap over the rivers of poop with ease.")
        print("Your speed and agility help you dodge every foul obstacle in the cavern, impressing even the poop monsters.")
        print("You sprint, jump, and flip through the maze, leaving a trail of awe-struck creatures behind.")
        print("Suddenly, a giant poop boulder rolls toward you! With a heroic vault, you clear it and land safely on the other side.")
        print("Victorious, you race onward, ready to tackle any challenge the poop-filled world throws your way!")
    if c==("b"):
        print("you have extraordinary memory. You step into the cavern, instantly recalling every detail from your past adventures.")
        print("You remember the exact layout of the poop rivers, the locations of hidden traps, and the secret signals used by the poop monsters.")
        print("Navigating the maze with confidence, you avoid every danger, retracing the steps of explorers who came before you.")
        print("Suddenly, you spot a mysterious inscription on the wall—it's a riddle you read in an ancient book years ago!")
        print("With your sharp memory, you solve the puzzle instantly, unlocking a hidden passage filled with sparkling treasures and magical cleaning supplies.")
        print("As you journey deeper, your memory helps you decode ancient maps, recall forgotten spells, and recognize friendly faces among the poop creatures.")
        print("You become a legend in the cavern, known as the Memory Master, helping others find their way and sharing stories of the past.")
        print("With every step, your remarkable memory guides you safely through the poop-filled world, turning every challenge into an opportunity for discovery and adventure!")
    if c==("c"):
        j=input("choose a name")
        print(j+" steps into the cavern, your detective instincts sharp as ever.")
        print("The air is thick and cold, shadows dancing along the walls.")
        print("they spot muddy footprints leading into a dark tunnel, and strange symbols smeared nearby.")
        print("Lights flicker overhead, and a distant howl echoes through the gloom.")
        print("their heart pounds, but they press on, analyzing every clue.")
        print("Suddenly, a monstrous figure emerges, its eyes glowing with hunger for fear.")
        print(j+" confronts the creature, using their detective skills to outsmart it.")
        print("With quick thinking, they find a hidden passage and rescue the missing explorer.")
        print("As they escape, "+j+" realizes some horrors never truly fade from memory.")
    if c==("d"):
        print("Being kid with a brainy mind, you enter the cavern with a notebook and flashlight, determined to solve its mysteries.")
        print("You notice strange equations etched into the slimy walls, glowing faintly in the darkness.")
        print("Your sharp intellect quickly deciphers the symbols—they're warnings left by explorers who vanished long ago.")
        print("Suddenly, the ground trembles and the air grows cold. Shadows twist into monstrous shapes, whispering riddles and threats.")
        print("You realize the cavern is alive, testing your intelligence with puzzles and traps at every turn.")
        print("A chilling wind blows out your flashlight, plunging you into darkness. You hear footsteps behind you, slow and deliberate.")
        print("Using your knowledge of acoustics, you clap your hands and listen for echoes, mapping the cavern in your mind.")
        print("You solve a series of terrifying riddles, each one unlocking a new passage deeper into the haunted maze.")
        print("The walls close in, and you feel icy fingers brush your shoulder. You remember a formula for escaping mazes and follow it, heart pounding.")
        print("Suddenly, you stumble upon a library of forbidden books guarded by a ghostly librarian with hollow eyes.")
        print("She challenges you to a battle of wits, asking questions about the darkest secrets of the universe.")
        print("You answer each one, your voice steady despite the fear clawing at your mind.")
        print("With every correct answer, the ghosts wail louder, and the cavern shakes, but you press on, determined to survive.")
        print("Finally, you reach the heart of the cavern—a swirling vortex of shadows and whispers.")
        print("You use your intelligence to decode the final riddle, banishing the darkness and freeing the trapped souls.")
        print("As you escape into the daylight, you realize your mind is your greatest weapon, and the horrors of the cavern will haunt your dreams forever.")
if a==("c"):
    d=input("choose hobby a: sports b: cooking c: art d: reading")
    if d==("a"):
        k=input("choose a name")
        print(k+" the cat was no ordinary feline—he was the star athlete of the underground poop cavern league. With their sleek fur and lightning-fast reflexes, he darted across the slippery terrain, dodging foul obstacles and leaping over rivers of sludge with ease. The poop monsters gathered to watch, amazed by their agility as they chased after the elusive golden poop ball, the prized trophy of the annual championship.")
        print("Every day, "+k+" trained hard, practicing their jumps, sprints, and tail-flick passes. their teammates, a motley crew of rats and frogs, relied on their leadership and clever strategies. The cavern echoed with cheers as they scored goal after goal, their paws barely touching the ground.")
        print("One day, the championship match arrived. The opposing team, led by the notorious Sludge Serpent, was fierce and determined to win. The game began with a flurry of action— "+k+" dashed through the muck, weaving between defenders and launching the ball with a powerful kick. The crowd roared as they performed a daring backflip, sending the ball soaring into the net.")
        print("But the Sludge Serpent wasn’t finished. It slithered across the field, blocking every move and hissing threats. they kept their cool, rallying their team and devising a clever play. With a swift pass and a perfectly timed leap, they outmaneuvered the serpent and scored the winning goal.")
        print("The cavern erupted in celebration. Whiskers was crowned champion, their name forever etched in the annals of poop cavern sports history. They raised the golden poop ball high, proud of their athletic prowess and the friendships they’d forged. From that day on, they inspired every creature in the cavern to chase their dreams—no matter how slippery the path might be.")
    if d==("b"):
        q=input("choose a name")
        print(q+" the cat was not just a master of agility—he was also the most talented chef in the poop cavern realm. With a tiny chef’s hat perched on his head and a whisk tucked behind his ear, Whiskers transformed the foulest ingredients into culinary masterpieces.")
        print("Every morning, he scoured the cavern for rare mushrooms, glowing slimeberries, and the freshest riverweed. In his cozy kitchen, he mixed, chopped, and stirred, creating dishes that made even the grumpiest poop monsters smile.")
        print("One day, the cavern announced its annual cooking contest. Whiskers entered with his signature dish: Poop Soufflé Surprise. The judges—an ancient rat, a wise frog, and the mysterious Sludge Serpent—watched as Whiskers worked his magic.")
        print("He whipped the riverweed into a frothy cloud, folded in the slimeberries, and sprinkled a dash of enchanted mushroom dust. The oven glowed, and the soufflé rose to perfection.")
        print("When the judges tasted his creation, their eyes widened in delight. The flavors danced on their tongues, and the cavern filled with cheers. Whiskers was crowned champion chef, his recipes passed down for generations.")
        print("From that day on, creatures from every corner of the cavern lined up for a taste of Whiskers's legendary cooking. He proved that even in the strangest places, a little creativity and a lot of heart could turn anything into something delicious.")
    if d==("c"):
        h=input("choose a name")
        print(h+" the cat was a true artist in the poop cavern, painting masterpieces on the slimy walls with his magical tail.")
        print("He mixed glowing slimeberries and river mud to create vibrant colors, transforming the dark cavern into a gallery of wonder.")
        print("Creatures from all around gathered to admire his work—portraits of heroic rats, dreamy landscapes, and swirling patterns that told ancient stories.")
        print("One day, Whiskers painted a mural so beautiful that even the grumpy poop monsters smiled and danced.")
        print("His art brought joy and hope to the cavern, proving that creativity could shine even in the strangest places.")
    if d==("d"):
        o=input("choose a name")
        print(o+" the cat loved to read more than anything else in the poop cavern. Every day, he curled up with a book beneath a glowing slimeberry lamp, his tail flicking with excitement as he turned each page.")
        print("He devoured stories about brave explorers, clever inventors, and magical lands far beyond the cavern walls. The other creatures watched in awe as Whiskers shared tales and facts, inspiring everyone to learn and dream.")
        print("One day, Whiskers discovered a mysterious ancient book hidden deep in the cavern. As he read aloud, the words shimmered and revealed a secret map to a treasure of enchanted soap.")
        print("With his love of reading and a curious mind, Whiskers led his friends on a grand adventure, attemping to find the lost treasure of gdffash. unfortunitely, whiskers was never seen again.")
if a==("d"):
    e=input("choose a food a: tacos b: spaghetti c: taffy d: pizza")
    if e==("a"):
        l=input("choose a name")
        print("my name is "+l+", and i drift silently through the bustling taco restaurant, invisible to the hungry humans.")
        print("I watch as they laugh and chat, their delicious tacos piled high with cheese, salsa, and spicy meats.")
        print("With a sly grin, I swoop down and snatch a taco right off someone's plate, leaving only a faint chill in the air.")
        print("The humans look around, confused, wondering where their tasty treat disappeared to.")
        print("I float away, savoring your stolen taco, and giggle as i plan my next delicious heist.")
        print("Soon, tales spread of the mysterious taco thief haunting the restaurant, and I become a legend among ghosts and humans alike!")
    if e==("b"):
        print("The baby ghost floated gently through the kitchen, drawn by the delicious smell of spaghetti simmering on the stove.")
        print("Curious and hungry, the little ghost watched as noodles twirled and sauce bubbled, filling the air with warmth and comfort.")
        print("With a giggle, the baby ghost tried to pick up a strand of spaghetti, but it slipped right through its tiny, transparent hands!")
        print("Undeterred, the ghost swooped down and wrapped itself around the bowl, hoping to taste the magical meal.")
        print("To its delight, the spaghetti tingled with ghostly flavor, making the baby ghost laugh and swirl with joy.")
        print("From that day on, the baby ghost became a spaghetti fan, haunting kitchens everywhere in search of another tasty bite!")
    if e==("c"):
        print("In the heart of the poop cavern, there lived a chubby ghost named Marshmallow. Marshmallow loved taffy more than anything else in the world—stretchy, chewy, and oh-so-sweet!")
        print("Every day, Marshmallow floated from candy shop to candy shop, gobbling up mountains of taffy in every color and flavor. His round belly grew bigger and bigger, wobbling as he drifted through the air.")
        print("The other ghosts giggled and cheered as Marshmallow performed silly tricks, bouncing and twirling like a fluffy cloud. Sometimes, he got stuck in doorways or floated upside down, all because of his taffy-filled tummy!")
        print("One day, Marshmallow ate so much taffy that he became the softest, squishiest ghost in the cavern. He gave the best hugs, and everyone loved to snuggle with him during story time.")
        print("From then on, Marshmallow shared his taffy with friends, spreading sweetness and laughter wherever he floated. And even though he was the fattest ghost around, he was also the happiest—proving that a little extra fluff and a lot of kindness make every day sweeter!")
    if e==("d"):
        print("BooBoo the ghost was the cutest spirit in the poop cavern—so adorable that everyone thought he was too timid for adventure.")
        print("The other ghosts teased him, saying he would never dare to try pizza, the most dangerous food for ghosts (because its cheesy goodness could trap a ghost in a gooey mess forever).")
        print("But BooBoo was determined to prove them wrong. One night, he floated into the haunted pizzeria, his cheeks glowing with courage.")
        print("He eyed the steaming pizza, piled high with stretchy cheese and spicy pepperoni. The other ghosts gasped, warning him to stay away.")
        print("With a brave giggle, BooBoo took a bite. The cheese stretched and tangled, but BooBoo spun and twirled, escaping every sticky trap with his nimble moves.")
        print("The pizza didn’t defeat him—instead, BooBoo’s cuteness and cleverness won the day! The other ghosts cheered, amazed by his bravery.")
        print("From then on, BooBoo was known as the bravest ghost in the cavern, proving that even the cutest spirits can conquer their fears and enjoy a slice of adventure!")