print("WELCOME TO QUIZ LABUBU!!! YOU WILL FIND OUT YOUR LABUBU BASED ON PERSONALITY.")
print("question one: what would you do on a sunny day? A: go to the beach B: go get ice cream with friends C: sleep in D: watch TV")
input("ytour answer: ")
print("2 what is your favorite ice cream flavor? A: chocolate B: mint chocolate chip C: chocolate chip D: vanilla with fudge")
input("ytour answer: ")
print("3 what is your favorite season? A: winter B: spring C: summer D: falll")
input("ytour answer: ")
print("4 what is your favorite music genre? A: pop/k-pop B: rock C: classical D: country")
input("ytour answer: ")
print("5 who do you spend most of your time with? A: mom B:dad C: friend D: sibling")
input("ytour answer: ")
print("6 when do you go to bed? A: 7 B:8 C: 10 D: i don't")
input("ytour answer: ")
print("mostly As: Zimomo mostly Bs: Tycoco mostly Cs: Mokoko mostly Ds: Pato")