k=input("animal:")
f=input("number:")
l=input("ajective: ")
h=input("food:")
o=input("name:")
s=input("country:")
u=input("noun:")
a=input("car")
print("HELLO! my name is"+k)
print("and i am" +f+" years old. I am also very "+l+", and my favorite thing to eat is"+h+ "i drive a "+a+". my mother is named "+ o +" and my family often goes to"+s+". One thing you may not know about me is that i have an obsession with"+u)
print("now you know your abc's")